### ISSUE TITLE
Request for the Model Code

### ISSUE THREAD

**Issue by uma-lal** [zhanghaoyue/DeepLearningFirstPassEffect#1]
Dear Harry Zhang,

I'm really interested in your "deep learning approach to predict recanalization first pass effect" project and was wondering if you could share the model code as mentioned. It would be very useful for replicating your results and conducting further research.

Thanks a lot, and looking forward to your reply!

Uma Lal

**Comment by zhanghaoyue** [comment]
Done. please  check.

**Comment by uma-lal** [comment]
Thank you!
